install:
    set QTDIR=C:\Qt\5.14.2\mingw73_32\bin &&
    set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
    C:\Qt\5.14.2\mingw73_32\bin\qmake Src.pro &&
    mingw32-make &&
    cd Test &&
    C:\Qt\5.14.2\mingw73_32\bin\qmake Test.pro &&
    mingw32-make
